# Generated by Django 4.1.2 on 2022-10-27 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_time_publication']},
        ),
    ]
