# Generated by Django 4.1.2 on 2022-10-23 14:20

from django.db import migrations, models
import workshop_petstagram.photos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='mediafiles/pet_photos/', validators=[workshop_petstagram.photos.validators.validate_file_size_less_than_5mb]),
        ),
    ]
